### ISSUE TITLE
Vulkan build support

### ISSUE THREAD

**Issue by shrinktofit** [pal1000/swiftshader-dist-win#1]
I found that only meson will build vulkan, but meson doesn't work on windows...

**Comment by pal1000** [comment]
TODO list for this issue:
- [x] implement build script basic parts;
- [x] implement build customization;
- [ ] collect binaries, libraries and headers (work in progress);
- [ ] implement automation with build customization;
- [ ] implement packaging and build bot.

**Comment by pal1000** [comment]
@damiandixon you'll find swiftshader binaries including Vulkan driver [here](https://dev.azure.com/bontarka/swiftshader-dist-win/_build?view=runs).
