### ISSUE TITLE
Can't run Vulkan demo in GPU Caps Viewer

### ISSUE THREAD

**Issue by maa7** [pal1000/swiftshader-dist-win#10]
Hello,
I installed the swiftshader, the program sees it, but the Vulcan demos do not work...
![swiftshadervk](https://github.com/pal1000/swiftshader-dist-win/assets/45234995/0dc71c95-ca76-4358-875b-11de47f194e5)

**Comment by pal1000** [comment]
Also post here: https://groups.google.com/g/swiftshader/
Try bisecting last month using my build too. Maybe it's a recent regression. I also need to warn you that 32-bit applications fixes have less priority.

**Comment by maa7** [comment]
I changed the version from LLVM to Subzero
Now the demo run fine! What is the difference between these versions?
![Uploading swiftshadervksz.png…]()

**Comment by pal1000** [comment]
subzero is a very light / minimalist CPU JIT created by Google originally forked from LLVM 4.0 based on some code artifacts while I looked at it a while ago.
