### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by SIsilicon** [pal1000/swiftshader-dist-win#5]
I'm trying to use this for debugging a vulkan application, but it doesn't seem to work. In your instructions in the README, it says to copy a vulkan dll, but I do not see any DLLs whatsoever. :/

**Comment by pal1000** [comment]
Updated readme to make it clearer where DLLs are found. I also added info about swiftshader vulkan setup tool which can run programs with swiftshader vulkan driver without any DLL copy by using Vulkan loader which ships with Vulkan enabled GPU drivers and can also be installed manually.

**Comment by SIsilicon** [comment]
Thank you kindly! Now I am one step closer to running applications with Vulkan. :)
