### ISSUE TITLE
Azure Pipelines on dev.azure.com are no longer producing artifacts

### ISSUE THREAD

**Issue by BlohoJo** [pal1000/swiftshader-dist-win#7]
Unable to download any of the latest binaries as the Azure pipelines have stopped producing artifacts.

https://dev.azure.com/bontarka/swiftshader-dist-win/_build?view=runs

The last run that produced artifacts (binaries) is 20201201.1:

https://dev.azure.com/bontarka/swiftshader-dist-win/_build/results?buildId=821&view=results

Starting with 20201201.2, no more artifacts are being published:

https://dev.azure.com/bontarka/swiftshader-dist-win/_build/results?buildId=822&view=results
https://dev.azure.com/bontarka/swiftshader-dist-win/_build/results?buildId=822&view=artifacts&pathAsName=false

**Comment by pal1000** [comment]
Not all runs produce artifacts. Citing from readme:
> Binaries packages are created automatically on Azure Pipelines every 8 hours if there are changes either here or with swiftshader itself. Builds will end quickly, under 10 minutes and with no binaries posted if there is no change.
